# - Find MD5SUM

# This module looks for MD5SUM. This module defines the following fields:
#
#  MD5SUM_EXECUTABLE  the path to the MD5SUM tool.
#  MD5SUM_FOUND       TRUE if MD5SUM has been found.

FIND_PROGRAM(MD5SUM_EXECUTABLE
  NAMES md5sum
  PATHS /usr/local/bin
        /usr/bin
)

IF (MD5SUM_EXECUTABLE)
  SET(MD5SUM_FOUND "Yes")
ELSE (MD5SUM_EXECUTABLE)
  SET(MD5SUM_FOUND "No")
ENDIF (MD5SUM_EXECUTABLE)

IF (MD5SUM_FOUND)
  IF (NOT MD5SUM_FIND_QUIETLY)
    MESSAGE(STATUS "Found MD5SUM: ${MD5SUM_EXECUTABLE}")
  ENDIF (NOT MD5SUM_FIND_QUIETLY)
ELSE (MD5SUM_FOUND)
  IF (MD5SUM_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could NOT find MD5SUM")
  ENDIF (MD5SUM_FIND_REQUIRED)
ENDIF (MD5SUM_FOUND)

MARK_AS_ADVANCED(MD5SUM_EXECUTABLE)

