# - Find strigicmd

# This module looks for strigicmd. This module defines the following fields:
#
#  STRIGICMD_EXECUTABLE  the path to the strigicmd tool.
#  STRIGICMD_FOUND       TRUE if strigicmd has been found.

FIND_PROGRAM(STRIGICMD_EXECUTABLE
  NAMES strigicmd
  PATHS /usr/local/bin
        /usr/bin
)

IF (STRIGICMD_EXECUTABLE)
  SET(STRIGICMD_FOUND "Yes")
ELSE (STRIGICMD_EXECUTABLE)
  SET(STRIGICMD_FOUND "No")
ENDIF (STRIGICMD_EXECUTABLE)

IF (STRIGICMD_FOUND)
  IF (NOT STRIGICMD_FIND_QUIETLY)
    MESSAGE(STATUS "Found STRIGICMD: ${STRIGICMD_EXECUTABLE}")
  ENDIF (NOT STRIGICMD_FIND_QUIETLY)
ELSE (STRIGICMD_FOUND)
  IF (STRIGICMD_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could NOT find STRIGICMD")
  ENDIF (STRIGICMD_FIND_REQUIRED)
ENDIF (STRIGICMD_FOUND)

MARK_AS_ADVANCED(STRIGICMD_EXECUTABLE)

